Db/cycle two
PairMhai/Backend pull request #39
Opened 2017-10-21 15:28 UTC by maymaays

## What kind of change does this PR introduce?
update promotion, design, and orderinfo
## Description
- delete product as be foreign key 
- add status field
- add new events
(promotion)
- add yard in design models
(design)
- add remarks (by using customer size)
(orderinfo)
## The PR fulfills these requirements:
- [ ] merge with latest version in `dev` branch
- [ ] run pass all testcase, if it have

## Other information:
...

2017-10-21 15:43 UTC, kamontat requested changes

2017-10-21 15:43 UTC, kamontat commented on cart/models.py
> +    remarks = models.CharField(max_length=100, default=0)
Change remark to Textfield

2017-10-21 15:43 UTC, kamontat commented on catalog/fixtures/init_promotion.yaml
>  - model: catalog.promotion
Change description to real description and move out date to different column 

Maybe separate to start date and end date column

2017-10-21 15:43 UTC, kamontat commented on catalog/models.py
> +        max_digits=8, decimal_places=2, default=0.00)
Did 8 digit is too long for design yard?

2017-10-21 18:11 UTC, maymaays commented
already edited code na ja

2017-10-22 07:05 UTC, kamontat approved these changes

2017-10-22 07:06 UTC, merged